# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'costadm_dialogsort_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogSort(object):
    def setupUi(self, DialogSort):
        DialogSort.setObjectName("DialogSort")
        DialogSort.resize(404, 265)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogSort)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(DialogSort)
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 381, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_col_1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_col_1.setObjectName("label_col_1")
        self.horizontalLayout.addWidget(self.label_col_1)
        self.combo_col_1 = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_col_1.setObjectName("combo_col_1")
        self.horizontalLayout.addWidget(self.combo_col_1)
        self.space = QtWidgets.QLabel(self.layoutWidget)
        self.space.setText("")
        self.space.setObjectName("space")
        self.horizontalLayout.addWidget(self.space)
        self.label_ord_1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_ord_1.setObjectName("label_ord_1")
        self.horizontalLayout.addWidget(self.label_ord_1)
        self.combo_ord_1 = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_ord_1.setObjectName("combo_ord_1")
        self.horizontalLayout.addWidget(self.combo_ord_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_col_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_col_2.setObjectName("label_col_2")
        self.horizontalLayout_2.addWidget(self.label_col_2)
        self.combo_col_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_col_2.setObjectName("combo_col_2")
        self.horizontalLayout_2.addWidget(self.combo_col_2)
        self.space_2 = QtWidgets.QLabel(self.layoutWidget)
        self.space_2.setText("")
        self.space_2.setObjectName("space_2")
        self.horizontalLayout_2.addWidget(self.space_2)
        self.label_ord_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_ord_2.setObjectName("label_ord_2")
        self.horizontalLayout_2.addWidget(self.label_ord_2)
        self.combo_ord_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_ord_2.setObjectName("combo_ord_2")
        self.horizontalLayout_2.addWidget(self.combo_ord_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_col_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_col_3.setObjectName("label_col_3")
        self.horizontalLayout_3.addWidget(self.label_col_3)
        self.combo_col_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_col_3.setObjectName("combo_col_3")
        self.horizontalLayout_3.addWidget(self.combo_col_3)
        self.space_3 = QtWidgets.QLabel(self.layoutWidget)
        self.space_3.setText("")
        self.space_3.setObjectName("space_3")
        self.horizontalLayout_3.addWidget(self.space_3)
        self.label_ord_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_ord_3.setObjectName("label_ord_3")
        self.horizontalLayout_3.addWidget(self.label_ord_3)
        self.combo_ord_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_ord_3.setObjectName("combo_ord_3")
        self.horizontalLayout_3.addWidget(self.combo_ord_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_col_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_col_4.setObjectName("label_col_4")
        self.horizontalLayout_4.addWidget(self.label_col_4)
        self.combo_col_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_col_4.setObjectName("combo_col_4")
        self.horizontalLayout_4.addWidget(self.combo_col_4)
        self.space_4 = QtWidgets.QLabel(self.layoutWidget)
        self.space_4.setText("")
        self.space_4.setObjectName("space_4")
        self.horizontalLayout_4.addWidget(self.space_4)
        self.label_ord_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_ord_4.setObjectName("label_ord_4")
        self.horizontalLayout_4.addWidget(self.label_ord_4)
        self.combo_ord_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_ord_4.setObjectName("combo_ord_4")
        self.horizontalLayout_4.addWidget(self.combo_ord_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_col_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_col_5.setObjectName("label_col_5")
        self.horizontalLayout_5.addWidget(self.label_col_5)
        self.combo_col_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_col_5.setObjectName("combo_col_5")
        self.horizontalLayout_5.addWidget(self.combo_col_5)
        self.space_5 = QtWidgets.QLabel(self.layoutWidget)
        self.space_5.setText("")
        self.space_5.setObjectName("space_5")
        self.horizontalLayout_5.addWidget(self.space_5)
        self.label_ord_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_ord_5.setObjectName("label_ord_5")
        self.horizontalLayout_5.addWidget(self.label_ord_5)
        self.combo_ord_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_ord_5.setObjectName("combo_ord_5")
        self.horizontalLayout_5.addWidget(self.combo_ord_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSort)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DialogSort)
        self.buttonBox.accepted.connect(DialogSort.accept)
        self.buttonBox.rejected.connect(DialogSort.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogSort)

    def retranslateUi(self, DialogSort):
        _translate = QtCore.QCoreApplication.translate
        DialogSort.setWindowTitle(_translate("DialogSort", "Classificar"))
        self.label_col_1.setText(_translate("DialogSort", "Coluna 1"))
        self.label_ord_1.setText(_translate("DialogSort", "Ordem"))
        self.label_col_2.setText(_translate("DialogSort", "Coluna 2"))
        self.label_ord_2.setText(_translate("DialogSort", "Ordem"))
        self.label_col_3.setText(_translate("DialogSort", "Coluna 3"))
        self.label_ord_3.setText(_translate("DialogSort", "Ordem"))
        self.label_col_4.setText(_translate("DialogSort", "Coluna 4"))
        self.label_ord_4.setText(_translate("DialogSort", "Ordem"))
        self.label_col_5.setText(_translate("DialogSort", "Coluna 5"))
        self.label_ord_5.setText(_translate("DialogSort", "Ordem"))

