# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'costadm_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CostAdm(object):
    def setupUi(self, CostAdm):
        CostAdm.setObjectName("CostAdm")
        CostAdm.resize(860, 668)
        self.centralwidget = QtWidgets.QWidget(CostAdm)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cost_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.cost_tab.setEnabled(True)
        self.cost_tab.setMinimumSize(QtCore.QSize(817, 524))
        self.cost_tab.setObjectName("cost_tab")
        self.structure = QtWidgets.QWidget()
        self.structure.setObjectName("structure")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.structure)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.table_cost_structure = QtWidgets.QTableView(self.structure)
        self.table_cost_structure.setObjectName("table_cost_structure")
        self.verticalLayout_4.addWidget(self.table_cost_structure)
        self.cost_tab.addTab(self.structure, "")
        self.quotes = QtWidgets.QWidget()
        self.quotes.setObjectName("quotes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.quotes)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table_quotes = QtWidgets.QTableView(self.quotes)
        self.table_quotes.setObjectName("table_quotes")
        self.verticalLayout_3.addWidget(self.table_quotes)
        self.cost_tab.addTab(self.quotes, "")
        self.prod_vols = QtWidgets.QWidget()
        self.prod_vols.setObjectName("prod_vols")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.prod_vols)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.table_prod_volumes = QtWidgets.QTableView(self.prod_vols)
        self.table_prod_volumes.setObjectName("table_prod_volumes")
        self.verticalLayout_5.addWidget(self.table_prod_volumes)
        self.cost_tab.addTab(self.prod_vols, "")
        self.custo_por_item = QtWidgets.QWidget()
        self.custo_por_item.setObjectName("custo_por_item")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.custo_por_item)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.table_costs_item = QtWidgets.QTableView(self.custo_por_item)
        self.table_costs_item.setObjectName("table_costs_item")
        self.verticalLayout_6.addWidget(self.table_costs_item)
        self.cost_tab.addTab(self.custo_por_item, "")
        self.custo_copacker = QtWidgets.QWidget()
        self.custo_copacker.setObjectName("custo_copacker")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.custo_copacker)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.table_costs_copacker = QtWidgets.QTableView(self.custo_copacker)
        self.table_costs_copacker.setObjectName("table_costs_copacker")
        self.verticalLayout_7.addWidget(self.table_costs_copacker)
        self.cost_tab.addTab(self.custo_copacker, "")
        self.custo_medio = QtWidgets.QWidget()
        self.custo_medio.setObjectName("custo_medio")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.custo_medio)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_costs_avg = QtWidgets.QTableView(self.custo_medio)
        self.table_costs_avg.setObjectName("table_costs_avg")
        self.verticalLayout.addWidget(self.table_costs_avg)
        self.cost_tab.addTab(self.custo_medio, "")
        self.verticalLayout_2.addWidget(self.cost_tab)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(621, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(96, 32))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setMaximumSize(QtCore.QSize(81, 32))
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        CostAdm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CostAdm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 24))
        self.menubar.setObjectName("menubar")
        self.menu_action = QtWidgets.QMenu(self.menubar)
        self.menu_action.setObjectName("menu_action")
        self.menuA_es = QtWidgets.QMenu(self.menubar)
        self.menuA_es.setObjectName("menuA_es")
        self.menuDados = QtWidgets.QMenu(self.menubar)
        self.menuDados.setObjectName("menuDados")
        CostAdm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CostAdm)
        self.statusbar.setObjectName("statusbar")
        CostAdm.setStatusBar(self.statusbar)
        self.load_bom = QtWidgets.QAction(CostAdm)
        self.load_bom.setObjectName("load_bom")
        self.create_bom_newage = QtWidgets.QAction(CostAdm)
        self.create_bom_newage.setObjectName("create_bom_newage")
        self.load_quotes = QtWidgets.QAction(CostAdm)
        self.load_quotes.setObjectName("load_quotes")
        self.load_prod = QtWidgets.QAction(CostAdm)
        self.load_prod.setObjectName("load_prod")
        self.export_costs = QtWidgets.QAction(CostAdm)
        self.export_costs.setObjectName("export_costs")
        self.create_bom = QtWidgets.QAction(CostAdm)
        self.create_bom.setObjectName("create_bom")
        self.calc_costs_item = QtWidgets.QAction(CostAdm)
        self.calc_costs_item.setObjectName("calc_costs_item")
        self.calc_costs_avg = QtWidgets.QAction(CostAdm)
        self.calc_costs_avg.setObjectName("calc_costs_avg")
        self.quit = QtWidgets.QAction(CostAdm)
        self.quit.setObjectName("quit")
        self.export_bom = QtWidgets.QAction(CostAdm)
        self.export_bom.setObjectName("export_bom")
        self.collapse = QtWidgets.QAction(CostAdm)
        self.collapse.setObjectName("collapse")
        self.expand = QtWidgets.QAction(CostAdm)
        self.expand.setObjectName("expand")
        self.sort = QtWidgets.QAction(CostAdm)
        self.sort.setObjectName("sort")
        self.menu_action.addAction(self.load_bom)
        self.menu_action.addAction(self.load_quotes)
        self.menu_action.addAction(self.load_prod)
        self.menu_action.addSeparator()
        self.menu_action.addAction(self.export_bom)
        self.menu_action.addAction(self.export_costs)
        self.menu_action.addSeparator()
        self.menu_action.addAction(self.quit)
        self.menuA_es.addAction(self.create_bom)
        self.menuA_es.addAction(self.create_bom_newage)
        self.menuA_es.addSeparator()
        self.menuA_es.addAction(self.calc_costs_item)
        self.menuA_es.addAction(self.calc_costs_avg)
        self.menuDados.addAction(self.collapse)
        self.menuDados.addAction(self.expand)
        self.menuDados.addAction(self.sort)
        self.menubar.addAction(self.menu_action.menuAction())
        self.menubar.addAction(self.menuA_es.menuAction())
        self.menubar.addAction(self.menuDados.menuAction())

        self.retranslateUi(CostAdm)
        self.cost_tab.setCurrentIndex(2)
        self.cost_tab.currentChanged['int'].connect(CostAdm.set_tab)
        self.pushButton_save.clicked.connect(CostAdm.save_table)
        self.pushButton_cancel.clicked.connect(CostAdm.del_table)
        self.menubar.triggered['QAction*'].connect(CostAdm.do_action)
        QtCore.QMetaObject.connectSlotsByName(CostAdm)

    def retranslateUi(self, CostAdm):
        _translate = QtCore.QCoreApplication.translate
        CostAdm.setWindowTitle(_translate("CostAdm", "Cálculo de Custos"))
        self.cost_tab.setTabText(self.cost_tab.indexOf(self.structure), _translate("CostAdm", "Estrutura"))
        self.cost_tab.setTabText(self.cost_tab.indexOf(self.quotes), _translate("CostAdm", "Cotações"))
        self.cost_tab.setTabText(self.cost_tab.indexOf(self.prod_vols), _translate("CostAdm", "Volumes de Produção"))
        self.cost_tab.setTabText(self.cost_tab.indexOf(self.custo_por_item), _translate("CostAdm", "Custos por Item"))
        self.cost_tab.setTabText(self.cost_tab.indexOf(self.custo_copacker), _translate("CostAdm", "Custos por Copacker"))
        self.cost_tab.setTabText(self.cost_tab.indexOf(self.custo_medio), _translate("CostAdm", "Custos Médios"))
        self.pushButton_cancel.setText(_translate("CostAdm", "Cancelar"))
        self.pushButton_save.setText(_translate("CostAdm", "Salvar"))
        self.menu_action.setTitle(_translate("CostAdm", "Arquivo"))
        self.menuA_es.setTitle(_translate("CostAdm", "Ações"))
        self.menuDados.setTitle(_translate("CostAdm", "Dados"))
        self.load_bom.setText(_translate("CostAdm", "Carregar Arquivo BOM ..."))
        self.load_bom.setToolTip(_translate("CostAdm", "Carregar Composição de Matérias Primas, Embalagens, Serviços, Logística"))
        self.create_bom_newage.setText(_translate("CostAdm", "Adicionar Arquivos NewAge a BOM ..."))
        self.create_bom_newage.setToolTip(_translate("CostAdm", "Carregar Composição de Matérias Primas, Embalagens, Serviços, Logística"))
        self.load_quotes.setText(_translate("CostAdm", "Carregar Cotações ..."))
        self.load_quotes.setToolTip(_translate("CostAdm", "Carregar arquivo com as cotações atuais dos várias Matérias Primas, Embalagens"))
        self.load_prod.setText(_translate("CostAdm", "Carregar Volumes de Produção ..."))
        self.export_costs.setText(_translate("CostAdm", "Exportar Custos para Excel ..."))
        self.create_bom.setText(_translate("CostAdm", "Adicionar Receita(s) a BOM ..."))
        self.calc_costs_item.setText(_translate("CostAdm", "Calcular Custos por Item /  Copacker"))
        self.calc_costs_avg.setText(_translate("CostAdm", "Calcular Custo Medio"))
        self.quit.setText(_translate("CostAdm", "Sair ..."))
        self.export_bom.setText(_translate("CostAdm", "Exportar BOM ..."))
        self.collapse.setText(_translate("CostAdm", "ContrairTabela"))
        self.expand.setText(_translate("CostAdm", "Expandir Tabela"))
        self.sort.setText(_translate("CostAdm", "Classificar ..."))

